import { z } from "zod";

import { ONE_LINE_REQUIRED_PATTERN } from "./text-rules.ts";
import type { SemanticValue } from "./widget-semantic.ts";

/**
 * Cards that show a piece of work: a block of code, a unified diff, a file.
 *
 * Everything on them is what the model wrote into their props, bounded by the schema. None of them fetches anything:
 * a file card names a file and says what it is, and has no link, no "open" and no download, because a reference to a
 * real artifact goes only through the node's own artifact broker, never through a URL a model wrote. The node's own
 * artifact and diff cards stay host-owned and are built from its records; these are catalog primitives beside them.
 *
 * One description serves the node and the page. The node refuses props that fail `artifactViewerProblems` before an
 * instance exists; the page reads the same props with `readArtifactViewer` and draws only what passes.
 */

export const MAX_CODE_CHARS = 20_000;
export const MAX_CODE_LINES = 400;
export const MAX_DIFF_FILES = 20;
export const MAX_DIFF_HUNKS = 20;
export const MAX_DIFF_LINES = 600;
export const MAX_DIFF_CHARS = 40_000;
export const MAX_DIFF_LINE_CHARS = 1000;
export const MAX_START_LINE = 10_000_000;

export const DIFF_LINE_KINDS = ["add", "remove", "context"] as const;
export type DiffLineKind = (typeof DIFF_LINE_KINDS)[number];

/** A language hint: a highlighter name or a file extension, never markup. */
export const LANGUAGE_PATTERN = "^[A-Za-z0-9][A-Za-z0-9_+#.-]{0,39}$";
/** A media type as `type/subtype`, with no parameters. */
export const MEDIA_TYPE_PATTERN = "^[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]{0,63}/[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]{0,63}$";
const oneLine = (max: number) => z.string().min(1).max(max).regex(new RegExp(ONE_LINE_REQUIRED_PATTERN, "u"));
const titleSchema = z.string().max(200);
const pathSchema = oneLine(300);

export const codeViewerSchema = z.strictObject({
  title: titleSchema.optional(),
  /** Where the code comes from, shown as text. */
  path: pathSchema.optional(),
  language: z.string().regex(new RegExp(LANGUAGE_PATTERN, "u")).optional(),
  code: z.string().min(1).max(MAX_CODE_CHARS),
  /** The number of the first line shown, when the code is an excerpt. */
  startLine: z.number().int().min(1).max(MAX_START_LINE).optional(),
  /** The model cut the code to fit: the card says so. */
  truncated: z.boolean().optional(),
});
export type CodeViewer = z.infer<typeof codeViewerSchema>;

export const diffLineSchema = z.strictObject({
  kind: z.enum(DIFF_LINE_KINDS),
  text: z.string().max(MAX_DIFF_LINE_CHARS),
});
export type DiffLine = z.infer<typeof diffLineSchema>;

export const diffHunkSchema = z.strictObject({
  /** The first line the hunk covers in the old file, 0 when the file is new. */
  oldStart: z.number().int().min(0).max(MAX_START_LINE),
  /** The first line the hunk covers in the new file, 0 when the file is deleted. */
  newStart: z.number().int().min(0).max(MAX_START_LINE),
  /** The enclosing function or section, as a diff header names it. */
  section: z.string().max(200).optional(),
  lines: z.array(diffLineSchema).min(1).max(MAX_DIFF_LINES),
});
export type DiffHunk = z.infer<typeof diffHunkSchema>;

export const diffFileSchema = z.strictObject({
  path: pathSchema,
  /** The path before a rename. */
  oldPath: pathSchema.optional(),
  hunks: z.array(diffHunkSchema).min(1).max(MAX_DIFF_HUNKS),
});
export type DiffFile = z.infer<typeof diffFileSchema>;

export const diffViewerSchema = z.strictObject({
  title: titleSchema.optional(),
  files: z.array(diffFileSchema).min(1).max(MAX_DIFF_FILES),
  /** The model left part of the change out: the card says so. */
  truncated: z.boolean().optional(),
});
export type DiffViewer = z.infer<typeof diffViewerSchema>;

export const fileViewerSchema = z.strictObject({
  title: titleSchema.optional(),
  name: oneLine(200),
  mediaType: z.string().max(128).regex(new RegExp(MEDIA_TYPE_PATTERN, "u")).optional(),
  sizeBytes: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER).optional(),
  /** Where the file came from, in words: "Generated by Clark", "Attached by Lan". */
  source: z.string().max(200).optional(),
  /** Where the file is, as text. Never a link. */
  path: oneLine(500).optional(),
  summary: z.string().max(500).optional(),
});
export type FileViewer = z.infer<typeof fileViewerSchema>;

export type ArtifactViewerKind = "code" | "diff" | "file";

export type ArtifactViewerContent =
  | { kind: "code"; card: CodeViewer }
  | { kind: "diff"; card: DiffViewer }
  | { kind: "file"; card: FileViewer };

/* ------------------------------------------------------------------ *
 * Counting
 * ------------------------------------------------------------------ */

/** The lines of a block of code. A final line break ends the last line; it does not start another. */
export function codeLines(code: string): string[] {
  const lines = code.split(/\r\n|\n|\r/u);
  if (lines.length > 1 && lines.at(-1) === "") lines.pop();
  return lines;
}

/** The first and last line numbers a code card shows. */
export function codeLineRange(card: Pick<CodeViewer, "code" | "startLine">): { first: number; last: number; count: number } {
  const count = codeLines(card.code).length;
  const first = card.startLine ?? 1;
  return { first, last: first + count - 1, count };
}

/**
 * The language to highlight: the one the model named, or the path's extension.
 *
 * Only a hint. A name the highlighter does not know shows the code as plain text, which is what an invented or
 * missing language should get.
 */
export function codeLanguage(card: Pick<CodeViewer, "language" | "path">): string | undefined {
  if (card.language !== undefined) return card.language;
  const name = card.path?.split(/[\\/]/u).at(-1) ?? "";
  const dot = name.lastIndexOf(".");
  if (dot <= 0 || dot === name.length - 1) return undefined;
  const extension = name.slice(dot + 1).toLowerCase();
  return new RegExp(LANGUAGE_PATTERN, "u").test(extension) ? extension : undefined;
}

/** A diff line with the numbers it has in the old and the new file. An added line has no old number, a removed one no new. */
export type NumberedDiffLine = DiffLine & { oldLine?: number; newLine?: number };

/** Each line of a hunk with its old and new line numbers, counted from the hunk's starts. */
export function numberedHunkLines(hunk: DiffHunk): NumberedDiffLine[] {
  let oldLine = hunk.oldStart;
  let newLine = hunk.newStart;
  return hunk.lines.map((line) => {
    if (line.kind === "add") return { ...line, newLine: newLine++ };
    if (line.kind === "remove") return { ...line, oldLine: oldLine++ };
    return { ...line, oldLine: oldLine++, newLine: newLine++ };
  });
}

/** How many lines of the old and new file a hunk covers. */
export function hunkCounts(hunk: DiffHunk): { oldCount: number; newCount: number } {
  let oldCount = 0;
  let newCount = 0;
  for (const line of hunk.lines) {
    if (line.kind !== "add") oldCount += 1;
    if (line.kind !== "remove") newCount += 1;
  }
  return { oldCount, newCount };
}

/** The hunk's header as a unified diff writes it, computed from its lines rather than taken from the model. */
export function hunkHeader(hunk: DiffHunk): string {
  const { oldCount, newCount } = hunkCounts(hunk);
  const section = hunk.section === undefined || hunk.section === "" ? "" : ` ${hunk.section}`;
  return `@@ -${String(hunk.oldStart)},${String(oldCount)} +${String(hunk.newStart)},${String(newCount)} @@${section}`;
}

/** Lines added and removed in one file, counted from its lines. */
export function diffFileCounts(file: DiffFile): { additions: number; deletions: number } {
  let additions = 0;
  let deletions = 0;
  for (const hunk of file.hunks) {
    for (const line of hunk.lines) {
      if (line.kind === "add") additions += 1;
      if (line.kind === "remove") deletions += 1;
    }
  }
  return { additions, deletions };
}

/** Lines added and removed across the whole diff. */
export function diffCounts(card: DiffViewer): { files: number; additions: number; deletions: number } {
  let additions = 0;
  let deletions = 0;
  for (const file of card.files) {
    const counts = diffFileCounts(file);
    additions += counts.additions;
    deletions += counts.deletions;
  }
  return { files: card.files.length, additions, deletions };
}

/* ------------------------------------------------------------------ *
 * Reading and checking
 * ------------------------------------------------------------------ */

function parsed(kind: ArtifactViewerKind, props: unknown): ArtifactViewerContent | undefined {
  if (kind === "code") {
    const result = codeViewerSchema.safeParse(props);
    return result.success ? { kind, card: result.data } : undefined;
  }
  if (kind === "diff") {
    const result = diffViewerSchema.safeParse(props);
    return result.success ? { kind, card: result.data } : undefined;
  }
  const result = fileViewerSchema.safeParse(props);
  return result.success ? { kind, card: result.data } : undefined;
}

function codeProblems(card: CodeViewer): string[] {
  const { count, last } = codeLineRange(card);
  const problems: string[] = [];
  if (count > MAX_CODE_LINES) {
    problems.push(`the code has ${String(count)} lines; a card shows at most ${String(MAX_CODE_LINES)}: cut it and set truncated`);
  }
  if (last > MAX_START_LINE) problems.push(`the last line would be number ${String(last)}, above ${String(MAX_START_LINE)}`);
  return problems;
}

function hunkProblems(file: DiffFile, hunk: DiffHunk, index: number, previous: DiffHunk | undefined): string[] {
  const where = `hunk ${String(index + 1)} of ${file.path}`;
  const problems: string[] = [];
  const { oldCount, newCount } = hunkCounts(hunk);
  if (hunk.lines.every((line) => line.kind === "context")) problems.push(`${where} changes nothing: it has no added or removed line`);
  if (hunk.oldStart === 0 && oldCount > 0) problems.push(`${where} starts at old line 0, so it can only add lines`);
  if (hunk.newStart === 0 && newCount > 0) problems.push(`${where} starts at new line 0, so it can only remove lines`);
  if (hunk.lines.some((line) => /[\r\n]/u.test(line.text))) problems.push(`${where} has a line holding a line break; give each line on its own`);
  if (previous !== undefined) {
    const before = hunkCounts(previous);
    if (hunk.oldStart < previous.oldStart + before.oldCount || hunk.newStart < previous.newStart + before.newCount) {
      problems.push(`${where} overlaps or comes before the hunk above it; hunks go in file order`);
    }
  }
  return problems;
}

function diffProblems(card: DiffViewer): string[] {
  const problems: string[] = [];
  let lines = 0;
  let chars = 0;
  const seen = new Set<string>();
  for (const file of card.files) {
    if (seen.has(file.path)) problems.push(`${file.path} appears twice; give each file once with all its hunks`);
    seen.add(file.path);
    file.hunks.forEach((hunk, index) => {
      problems.push(...hunkProblems(file, hunk, index, index === 0 ? undefined : file.hunks[index - 1]));
      lines += hunk.lines.length;
      for (const line of hunk.lines) chars += line.text.length;
    });
  }
  if (lines > MAX_DIFF_LINES) problems.push(`the diff has ${String(lines)} lines; a card shows at most ${String(MAX_DIFF_LINES)}: cut it and set truncated`);
  if (chars > MAX_DIFF_CHARS) problems.push(`the diff holds ${String(chars)} characters; a card shows at most ${String(MAX_DIFF_CHARS)}: cut it and set truncated`);
  return problems;
}

/** A URL scheme at the start of a path: a file card names a file, it never links one. */
const URL_LIKE = /^[A-Za-z][A-Za-z0-9+.-]*:\/\//u;

function fileProblems(card: FileViewer): string[] {
  const problems: string[] = [];
  if (/[\\/]/u.test(card.name)) problems.push("the name is the file's own name; put the folder in path");
  if (card.path !== undefined && URL_LIKE.test(card.path)) {
    problems.push("a file card names a file and does not link one; a path that is a URL is refused");
  }
  return problems;
}

/** Everything wrong with a card's props: what the schema says, then what it cannot say. */
export function artifactViewerProblems(kind: ArtifactViewerKind, props: unknown): string[] {
  const content = parsed(kind, props);
  if (content === undefined) return [`the props do not describe a ${kind} card`];
  if (content.kind === "code") return codeProblems(content.card);
  if (content.kind === "diff") return diffProblems(content.card);
  return fileProblems(content.card);
}

/** The card its props describe, or `undefined` when the node would refuse them. */
export function readArtifactViewer(kind: ArtifactViewerKind, props: unknown): ArtifactViewerContent | undefined {
  const content = parsed(kind, props);
  return content !== undefined && artifactViewerProblems(kind, props).length === 0 ? content : undefined;
}

/* ------------------------------------------------------------------ *
 * What the card says, as text and as semantic state
 * ------------------------------------------------------------------ */

/** The most a snapshot's text alternative may hold. */
export const ARTIFACT_TEXT_LIMIT = 4000;

/** Text cut to a limit, saying how much was left out rather than ending mid-line as though that were all. */
function clipped(text: string, limit: number): string {
  if (text.length <= limit) return text;
  const note = (left: number) => `\n… ${String(left)} more characters are on the card`;
  // The note is shorter when fewer characters are left out, so keep grows until the two fill the limit exactly.
  let keep = limit - note(text.length).length;
  while (keep + 1 + note(text.length - keep - 1).length <= limit) keep += 1;
  return `${text.slice(0, keep)}${note(text.length - keep)}`;
}

function sizeText(bytes: number): string {
  return `${String(bytes)} byte${bytes === 1 ? "" : "s"}`;
}

/**
 * The card as plain text: the text alternative a reader gets when it cannot be drawn.
 *
 * Code and diffs keep their lines, so a transcript that outlives the renderer still holds the change; a body too long
 * for a snapshot says how much it left out.
 */
export function artifactViewerText(content: ArtifactViewerContent, limit = ARTIFACT_TEXT_LIMIT): string {
  const title = content.card.title !== undefined && content.card.title !== "" ? `${content.card.title}: ` : "";
  if (content.kind === "code") {
    const card = content.card;
    const { first, last } = codeLineRange(card);
    const cut = card.truncated === true ? ", cut short" : "";
    const head = `${title}${card.path ?? "Code"} (${codeLanguage(card) ?? "text"}, lines ${String(first)}-${String(last)}${cut})`;
    return clipped(`${head}\n${card.code}`, limit);
  }
  if (content.kind === "diff") {
    const card = content.card;
    const counts = diffCounts(card);
    const cut = card.truncated === true ? "; part of the change is left out" : "";
    const head = `${title}${String(counts.files)} file(s) changed, +${String(counts.additions)} -${String(counts.deletions)}${cut}`;
    const body = card.files.map((file) => {
      const fileCounts = diffFileCounts(file);
      const renamed = file.oldPath === undefined ? "" : `${file.oldPath} -> `;
      const hunks = file.hunks.map((hunk) => {
        const lines = hunk.lines.map((line) => `${line.kind === "add" ? "+" : line.kind === "remove" ? "-" : " "}${line.text}`);
        return [hunkHeader(hunk), ...lines].join("\n");
      });
      return [`${renamed}${file.path} +${String(fileCounts.additions)} -${String(fileCounts.deletions)}`, ...hunks].join("\n");
    });
    return clipped([head, ...body].join("\n"), limit);
  }
  const card = content.card;
  const facts = [card.mediaType, card.sizeBytes === undefined ? undefined : sizeText(card.sizeBytes)].filter(
    (fact): fact is string => fact !== undefined,
  );
  const parts = [
    `${title}${card.name}${facts.length === 0 ? "" : ` (${facts.join(", ")})`}`,
    card.source === undefined || card.source === "" ? undefined : `from ${card.source}`,
    card.path === undefined ? undefined : `at ${card.path}`,
  ].filter((part): part is string => part !== undefined);
  const summary = card.summary === undefined || card.summary === "" ? "" : `. ${card.summary}`;
  return clipped(`${parts.join(", ")}${summary}`, limit);
}

/**
 * What the card means for voice and `inspect_ui`: names, a language, line counts; never the code itself.
 *
 * Bounded by `normalizeSemanticDoc` afterwards. The body stays out: a summary that read a whole file aloud would be a
 * worse answer to "what is this" than its name, language and size.
 */
export function artifactViewerSemantic(content: ArtifactViewerContent): {
  title?: string;
  summary: string;
  values: Record<string, SemanticValue>;
} {
  const title = content.card.title !== undefined && content.card.title !== "" ? { title: content.card.title } : {};
  if (content.kind === "code") {
    const card = content.card;
    const { first, last, count } = codeLineRange(card);
    const language = codeLanguage(card) ?? "text";
    const truncated = card.truncated === true;
    return {
      ...title,
      summary:
        `Code as stated when shown: ${card.path ?? "untitled"} (${language}), ${String(count)} line(s), ` +
        `lines ${String(first)}-${String(last)}${truncated ? ", cut short" : ""}`,
      values: {
        ...(card.path === undefined ? {} : { path: card.path }),
        language,
        lineCount: count,
        firstLine: first,
        lastLine: last,
        truncated,
      },
    };
  }
  if (content.kind === "diff") {
    const card = content.card;
    const counts = diffCounts(card);
    const truncated = card.truncated === true;
    return {
      ...title,
      summary:
        `Diff as stated when shown: ${String(counts.files)} file(s), ${String(counts.additions)} line(s) added, ` +
        `${String(counts.deletions)} removed${truncated ? "; part of the change is left out" : ""}`,
      values: {
        fileCount: counts.files,
        linesAdded: counts.additions,
        linesRemoved: counts.deletions,
        files: card.files.map((file) => {
          const fileCounts = diffFileCounts(file);
          return `${file.path} +${String(fileCounts.additions)} -${String(fileCounts.deletions)}`;
        }),
        truncated,
      },
    };
  }
  const card = content.card;
  return {
    ...title,
    summary: `File as stated when shown: ${card.name}${card.mediaType === undefined ? "" : ` (${card.mediaType})`}`,
    values: {
      name: card.name,
      ...(card.mediaType === undefined ? {} : { mediaType: card.mediaType }),
      ...(card.sizeBytes === undefined ? {} : { sizeBytes: card.sizeBytes }),
      ...(card.source === undefined || card.source === "" ? {} : { source: card.source }),
      ...(card.path === undefined ? {} : { path: card.path }),
    },
  };
}
